function scienceGo(route){route=String(route);if(parent!==window)parent.postMessage({educationPlusRoute:route},location.origin);else location.href=(/^[A-Z]/.test(String(window.EP_PAGE||''))?'../':'')+'index.html#'+route}
function scienceToast(message){let t=document.querySelector('.toast');if(!t){t=document.createElement('div');t.className='toast';document.body.append(t)}t.textContent=message;t.classList.add('show');clearTimeout(window.__scienceToast);window.__scienceToast=setTimeout(()=>t.classList.remove('show'),1800)}
function switchSciencePanel(name,button){document.querySelectorAll('.tabs button').forEach(x=>x.classList.toggle('active',x===button));document.querySelectorAll('.panel').forEach(x=>x.hidden=x.dataset.panel!==name)}
function chooseVideoMode(button,mode){document.querySelectorAll('.seg button').forEach(x=>x.classList.toggle('active',x===button));document.getElementById('videoUploadGroup').hidden=mode!=='upload';document.getElementById('videoLinkGroup').hidden=mode!=='link';document.getElementById('videoMode').value=mode}
function submitTreasure(event){event.preventDefault();if(!event.currentTarget.reportValidity())return;const mode=document.getElementById('videoMode').value;localStorage.setItem('ep-science-treasure',JSON.stringify({status:'审核中',mode,date:new Date().toISOString()}));scienceToast('作品已提交，进入内容审核');setTimeout(()=>scienceGo('K04'),700)}
function submitQuestion(event){event.preventDefault();if(!event.currentTarget.reportValidity())return;const name=document.getElementById('studentName').value.trim();const school=document.getElementById('school').value.trim();localStorage.setItem('ep-science-question',JSON.stringify({status:'待对接专家',name,school,date:new Date().toISOString()}));scienceToast('问题已提交，我们将线下对接专家');setTimeout(()=>scienceGo('K04'),800)}
function filterScienceStatus(kind,button){document.querySelectorAll('.status-tabs button').forEach(x=>x.classList.toggle('active',x===button));document.querySelectorAll('.status-card').forEach(x=>x.hidden=kind!=='all'&&x.dataset.kind!==kind)}
function hydrateScienceStatus(){if(localStorage.getItem('ep-science-treasure'))document.querySelector('[data-live=treasure]')?.removeAttribute('hidden');if(localStorage.getItem('ep-science-question'))document.querySelector('[data-live=question]')?.removeAttribute('hidden')}
document.addEventListener('DOMContentLoaded',hydrateScienceStatus)
