const SUB_KEY='ep-subscription-flow-v2';
const SUB_DEFAULT={customerType:'personal',plan:'annual',price:288,method:'A',recipient:'张老师',phone:'13900001234',organization:'贵阳市第一实验中学',taxId:'',invoiceEmail:'teacher@example.com',invoicePhone:'13900001234'};
function subState(){try{return Object.assign({},SUB_DEFAULT,JSON.parse(localStorage.getItem(SUB_KEY)||'{}'))}catch(e){return {...SUB_DEFAULT}}}
function saveSub(patch){const next=Object.assign(subState(),patch);localStorage.setItem(SUB_KEY,JSON.stringify(next));return next}
function subGo(route){route=String(route);if(parent!==window)parent.postMessage({educationPlusRoute:route},location.origin);else location.href=(window.EP_PAGE?'../':'')+'index.html#'+route}
function subToast(message){let t=document.querySelector('.toast');if(!t){t=document.createElement('div');t.className='toast';document.body.append(t)}t.textContent=message;t.classList.add('show');clearTimeout(window.__subToast);window.__subToast=setTimeout(()=>t.classList.remove('show'),1900)}
function setCustomer(type){const s=subState();saveSub({customerType:type,method:type==='organization'&&s.method==='A'?'B':s.method});renderSubscription();if(type==='organization'&&s.method==='A')subToast('单位订阅已切换为线下支付方式')}
function setPlan(plan){saveSub(plan==='quarterly'?{plan:'quarterly',price:72}:{plan:'annual',price:288});renderSubscription()}
function setPayment(method){saveSub({method});renderSubscription()}
function methodName(method){return {A:'个人微信在线支付',B:'已线下支付并提交凭证',C:'先申请开票后支付'}[method]||'个人微信在线支付'}
function typeName(type){return type==='organization'?'单位订阅':'个人订阅'}
function showDialPrompt(){document.getElementById('dialDialog')?.removeAttribute('hidden')}
function hideDialPrompt(){document.getElementById('dialDialog')?.setAttribute('hidden','')}
function confirmDial(){hideDialPrompt();subToast('原型演示：手机端将调起拨号 0851-85531313')}
function copyAccount(){navigator.clipboard?.writeText('户名：贵州教育报传媒有限责任公司\n开户行：贵阳银行东山支行\n账号：151 401 200 3000 0433\n行号：313701007029');subToast('对公账户信息已复制（演示）')}
function renderSubscription(){const s=subState();document.querySelectorAll('[data-customer]').forEach(el=>el.classList.toggle('active',el.dataset.customer===s.customerType));document.querySelectorAll('[data-plan]').forEach(el=>el.classList.toggle('active',el.dataset.plan===s.plan));document.querySelectorAll('[data-method]').forEach(el=>el.classList.toggle('active',el.dataset.method===s.method));document.querySelectorAll('[data-only-method]').forEach(el=>el.hidden=!el.dataset.onlyMethod.includes(s.method));document.querySelectorAll('[data-only-type]').forEach(el=>el.hidden=!el.dataset.onlyType.includes(s.customerType));document.querySelectorAll('[data-method-name]').forEach(el=>el.textContent=methodName(s.method));document.querySelectorAll('[data-type-name]').forEach(el=>el.textContent=typeName(s.customerType));document.querySelectorAll('[data-plan-name]').forEach(el=>el.textContent=s.plan==='annual'?'年度订阅':'季度订阅');document.querySelectorAll('[data-price]').forEach(el=>el.textContent='¥'+s.price+'.00');const org=document.getElementById('organizationName');if(org&&!org.matches(':focus'))org.value=s.organization||'';const tax=document.getElementById('taxId');if(tax&&!tax.matches(':focus'))tax.value=s.taxId||'';const email=document.getElementById('invoiceEmail');if(email&&!email.matches(':focus'))email.value=s.invoiceEmail||'';const phone=document.getElementById('invoicePhone');if(phone&&!phone.matches(':focus'))phone.value=s.invoicePhone||''}
function startSubscription(){subGo('N01')}
function fakeUpload(el){el.innerHTML='<b>✓ 汇款凭证已选择</b><br><small>transfer-proof-demo.jpg · 原型演示</small>';saveSub({proof:true});subToast('汇款凭证已添加')}
function submitOrder(e){e.preventDefault();if(!e.currentTarget.reportValidity())return;const data=new FormData(e.currentTarget);saveSub({recipient:data.get('recipient'),phone:data.get('phone'),organization:data.get('organization')||subState().organization});const s=subState();if(s.method==='C'){subToast('请先提交电子发票申请');setTimeout(()=>subGo('N04'),600)}else{saveSub({orderSubmitted:true});subToast(s.method==='A'?'正在进入微信支付演示':'汇款凭证已提交，等待核验');setTimeout(()=>subGo('N02'),600)}}
const TAX_DEMO={'贵阳市第一实验中学':'91520100DEMO00001X','贵州师范大学附属中学':'91520100DEMO00002Q','贵州省实验中学':'91520000DEMO00003M'};
function matchTaxId(){const org=document.getElementById('organizationName');const tax=document.getElementById('taxId');const hint=document.getElementById('taxMatchHint');if(!org||!tax)return;const value=org.value.trim();saveSub({organization:value});if(TAX_DEMO[value]){tax.value=TAX_DEMO[value];saveSub({taxId:tax.value});hint.textContent='✓ 已匹配演示税号，请提交前核对真实信息';hint.className='match'}else{tax.value='';saveSub({taxId:''});hint.textContent=value?'未找到演示数据，请手动填写并核对税号':'输入完整单位名称后自动匹配';hint.className='match warn'}}
function submitInvoice(e){e.preventDefault();if(!e.currentTarget.reportValidity())return;const data=new FormData(e.currentTarget);saveSub({organization:data.get('organization'),taxId:data.get('taxId'),invoiceEmail:data.get('invoiceEmail'),invoicePhone:data.get('invoicePhone'),invoiceSubmitted:true});subToast('电子发票申请已提交');setTimeout(()=>subGo('N05'),650)}
document.addEventListener('DOMContentLoaded',renderSubscription);
